version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: America/Santiago
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope
    groups:
      dev-dependencies:
        dependency-type: development
      chakra-three:
        patterns:
          - '@chakra-ui/*'
          - '@react-three/*'
          - 'three'
          - 'framer-motion'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    labels:
      - ci
    commit-message:
      prefix: ci
